### Read Books Admin Entities
GET http://localhost:6420/admin-catalog/

### Read Books as Admin
GET http://localhost:6420/admin-catalog/Books
Authorization: Bearer {{$dotenv token}}

### Create a new Books as Admin
POST http://localhost:6420/admin-catalog/Books
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
  "ID": 20000,
  "title": "20.000 Meilen unter dem Meer",
  "stock": 20
}

### Create a new Books as Admin
PATCH http://localhost:6420/admin-catalog/Books(20000)
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
  "stock": 30
}

### Delete a Books as Admin
DELETE http://localhost:6420/admin-catalog/Books(20000)
Authorization: Bearer {{$dotenv token}}