### 
# @name getAccessToken
POST https://login.microsoftonline.com/{{$dotenv tenant}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv client_id}}
&scope=https://graph.microsoft.com/.default
&client_secret={{$dotenv client_secret}}
&grant_type=client_credentials

### Read Token to Variable
@access_token={{getAccessToken.response.body.access_token}}

###
GET https://graph.microsoft.com/beta/$metadata
Authorization: Bearer {{access_token}}

###
GET https://graph.microsoft.com/v1.0/$metadata
  ?$filter=otherMails/any(x:x eq '{{$dotenv mail}}')
Authorization: Bearer {{access_token}}

### All Users
GET https://graph.microsoft.com/beta/{{$dotenv tenant}}/users
Authorization: Bearer {{access_token}}

###
# @name singleUser
GET https://graph.microsoft.com/v1.0/users
  ?$filter=mail eq '{{$dotenv mail}}'
Authorization: Bearer {{access_token}}

### 
@userid={{singleUser.response.body.value[0].id}}

###
GET https://graph.microsoft.com/v1.0/users
  ?$filter=otherMails/any(x:x eq '{{$dotenv mail}}')
Authorization: Bearer {{access_token}}

### All Users
GET https://graph.microsoft.com/beta/{{$dotenv tenant}}/users/
  ?$filter=otherMails/any(x:x eq '{{$dotenv mail}}')
  &$inlinecount=true
Authorization: Bearer {{access_token}}

### All Users
GET https://graph.microsoft.com/beta/{{$dotenv tenant}}/users/
  ?$filter=mail eq '{{$dotenv mail}}'
  &$inlinecount=true
Authorization: Bearer {{access_token}}


### Specific user
GET https://graph.microsoft.com/beta/{{$dotenv tenant}}/users/{{$dotenv user}}
Authorization: Bearer {{access_token}}

### Update Specific user
PATCH https://graph.microsoft.com/beta/{{$dotenv tenant}}/users/{{$dotenv user}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "extension_{{$dotenv b2c-extensions-app}}_b2cgroups": "admin",
}


###
GET https://graph.microsoft.com/beta/users/{{userid}}/chats
Authorization: Bearer {{access_token}}

@chatid=10
###
POST https://graph.microsoft.com/v1.0/chats/{{chatid}}/sendActivityNotification
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "topic": {
        "source": "entityUrl",
        "value": "https://graph.microsoft.com/v1.0/chats/{{chatid}}"
    },
    "activityType": "taskCreated",
    "previewText": {
        "content": "New Task Created"
    },
    "recipient": {
        "@odata.type": "microsoft.graph.aadUserNotificationRecipient",
        "userId": "{{userid}}"
    },
    "templateParameters": [
        {
            "name": "taskId",
            "value": "Task 12322"
        }
    ] 
}

###
POST https://graph.microsoft.com/beta/chats/{{chatid}}/sendActivityNotification
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "topic": {
        "source": "entityUrl",
        "value": "https://graph.microsoft.com/beta/chats/{{chatid}}"
    },
    "activityType": "taskCreated",
    "previewText": {
        "content": "New Task Created"
    },
    "recipient": {
        "@odata.type": "microsoft.graph.aadUserNotificationRecipient",
        "userId": "{{$dotenv mail}}"
    },
    "templateParameters": [
        {
            "name": "taskId",
            "value": "Task 12322"
        }
    ] 
}

###
POST https://graph.microsoft.com/beta/users/{{userid}}/teamwork/sendActivityNotification
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "topic": {
        "source": "entityUrl",
        "value": "https://graph.microsoft.com/beta/users/{{userid}}/teamwork/installedApps/{installationId}"
    },
    "activityType": "taskCreated",
    "previewText": {
        "content": "New Task Created"
    },
    "templateParameters": [
        {
            "name": "taskId",
            "value": "Task 12322"
        }
    ]
}