### Read Books Authenticated User Entities
GET http://localhost:6420/odata/v4/catalog/

### Read list of entities as Authenticated User
GET http://localhost:6420/odata/v4/catalog/
Authorization: Bearer {{$dotenv token}}
### Read Books as Authenticated User
GET http://localhost:6420/odata/v4/catalog/Books
Authorization: Bearer {{$dotenv token}}
### Read Books as Authenticated User
GET http://localhost:6420/odata/v4/catalog/Products
  ?$filter=IsActiveEntity eq true
  &$top=10
Authorization: Bearer {{$dotenv token}}
###
POST http://localhost:6420/odata/v4/catalog/getOAuth2SAMLBearerAssertion
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{}
### Read SAP Logon Ticket
# @name readSAPLogonTicket
POST http://localhost:6420/odata/v4/catalog/readSAPLogonTicket
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{}
### Read Token to Variable
@ticket={{readSAPLogonTicket.response.body.value}}

###
GET {{$dotenv server}}/sap/public/ping

###
GET {{$dotenv server}}/sap/bc/zbiscuit
cookie: MYSAPSSO2={{ticket}}

###
GET {{$dotenv server}}/sap/bc/zbiscuit
cookie: MYSAPSSO2={{$dotenv ticket}}
